# Created by trellis-cli v1.6.1
# Documentation: https://docs.roots.io/trellis/master/wordpress-sites/

wordpress_sites:
  example.com:
    site_hosts:
    - canonical: example.com
      redirects:
      - www.example.com
    local_path: ../site
    branch: master
    repo: git@github.com:example/example.com.git
    repo_subtree_path: site
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: letsencrypt
    cache:
      enabled: false
